### ISSUE TITLE
Nokogiri Error

### ISSUE THREAD

**Issue by gaven** [algolia/algoliasearch-jekyll#55] opened 2017-08-02 16:30 UTC
When running `bundle exec jekyll algolia push` on Jekyll version 3.5.1 I get an error: `Error: undefined method 'parent' for #<Nokogiri::HTML::Document:0x007f8aabde5fc0>`.

I'm running Ruby version 2.3.0. Any ideas? Or anyone else experiencing this issue?

Thanks!

**Comment by redox** [comment] 2017-08-02 16:54
Arg, this might be related to the recent upgrade we did. Could you try downgrading to Nokogiri `1.6.x` and algoliasearch-jekyll `0.8.0` ?

**Comment by redox** [comment] 2017-08-02 16:58
@gavenheim could you provide us the backtrace?

**Comment by gaven** [comment] 2017-08-02 17:59
Hey, thanks for your response. I seemed to have figured it out. It looks like some inline styles were causing the error. Thanks for your time.

**Comment by redox** [comment] 2017-08-02 20:38
> Hey, thanks for your response. I seemed to have figured it out. It looks like some inline styles were causing the error. Thanks for your time.

Would love to still  handle that on our side; do you still have a backtrace so we can `rescue` it from here?

**Comment by bdombro** [comment] 2017-08-28 17:54
I had the same error, even when forcing Noko 1.6.x and AlgS 0.8.0. I found that this snippet is causing the error:

```
---
title: Services
heading: "Reliable and Fast Web Services"
subtitle: We build websites, campaigns and sales workflows for high achievers.
description: We build websites, campaigns and sales workflows for high achievers.
image: /images/benevolent_tech_dc_seo.png
---

<style>
    /* Hide the newsletter signup */
    .diagonal-newsletter {
        display: none;
    }
</style>
```

Log:
```
[13:52:09] Using gulpfile ~/Work/Clients/Benevolent_Tech/Projects/Website V4/bt-jekyll-website/gulpfile.js
[13:52:09] Starting 'css'...
[13:52:09] Starting 'js-libs'...
[13:52:09] Starting 'js-custom'...
[13:52:09] Finished 'css' after 32 ms
[13:52:10] Finished 'js-custom' after 400 ms
[13:52:10] Finished 'js-libs' after 406 ms
[13:52:10] Starting 'js-production'...
[13:52:10] Finished 'js-production' after 100 ms
[13:52:10] Starting 'jekyll-build'...
Configuration file: /Users/briandombrowski/Work/Clients/Benevolent_Tech/Projects/Website V4/bt-jekyll-website/_config.yml
       Deprecation: The 'gems' configuration option has been renamed to 'plugins'. Please update your config file accordingly.
            Source: /Users/briandombrowski/Work/Clients/Benevolent_Tech/Projects/Website V4/bt-jekyll-website
       Destination: /Users/briandombrowski/Work/Clients/Benevolent_Tech/Projects/Website V4/bt-jekyll-website/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
         AutoPages: Disabled/Not configured in site.config.
        Pagination: Is enabled, but I couldn't find any pagination page. Skipping pagination. Pages must have 'pagination: enabled: true' in their front-matter for pagination to work.
        Pagination: Complete, processed pagination page(s)
/Users/briandombrowski/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/nokogiri-1.6.7.2/lib/nokogiri/html/document.rb:164: warning: constant ::Fixnum is deprecated
/Users/briandombrowski/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/nokogiri-1.6.7.2/lib/nokogiri/html/document.rb:164: warning: constant ::Fixnum is deprecated
/Users/briandombrowski/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node.rb:389: warning: constant ::Fixnum is deprecated
                    done in 1.32 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
[13:52:12] Finished 'jekyll-build' after 2.07 s
[13:52:12] Starting 'build-all'...
[13:52:12] Finished 'build-all' after 72 μs
[13:52:12] Starting 'algolia-push'...
Configuration file: /Users/briandombrowski/Work/Clients/Benevolent_Tech/Projects/Website V4/bt-jekyll-website/_config.yml
       Deprecation: The 'gems' configuration option has been renamed to 'plugins'. Please update your config file accordingly.
         AutoPages: Disabled/Not configured in site.config.
        Pagination: Is enabled, but I couldn't find any pagination page. Skipping pagination. Pages must have 'pagination: enabled: true' in their front-matter for pagination to work.
        Pagination: Complete, processed pagination page(s)
/Users/briandombrowski/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/nokogiri-1.6.7.2/lib/nokogiri/html/document.rb:164: warning: constant ::Fixnum is deprecated
/Users/briandombrowski/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/nokogiri-1.6.7.2/lib/nokogiri/html/document.rb:164: warning: constant ::Fixnum is deprecated
/Users/briandombrowski/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node.rb:389: warning: constant ::Fixnum is deprecated
/Users/briandombrowski/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/nokogiri-1.6.7.2/lib/nokogiri/html/document.rb:164: warning: constant ::Fixnum is deprecated
jekyll 3.5.2 | Error:  undefined method `parent' for #<Nokogiri::HTML::Document:0x007ffbade1c250>
Did you mean?  parent=
[13:52:14] 'algolia-push' errored after 1.81 s
[13:52:14] Error: 1
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at emitOne (events.js:115:13)
    at Gulp.emit (events.js:210:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/briandombrowski/Work/Clients/Benevolent_Tech/Projects/Website V4/bt-jekyll-website/node_modules/orchestrator/index.js:264:8)
    at /Users/briandombrowski/Work/Clients/Benevolent_Tech/Projects/Website V4/bt-jekyll-website/node_modules/orchestrator/index.js:275:23
    at finish (/Users/briandombrowski/Work/Clients/Benevolent_Tech/Projects/Website V4/bt-jekyll-website/node_modules/orchestrator/lib/runTask.js:21:8)
    at ChildProcess.cb (/Users/briandombrowski/Work/Clients/Benevolent_Tech/Projects/Website V4/bt-jekyll-website/node_modules/orchestrator/lib/runTask.js:29:3)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
```

**Comment by pixelastic** [comment] 2017-10-30 11:01
I think this error is coming from the fact that we are trying to extract all `<p>` (by default) from the generated page. In the example you're providing, there are no `<p>` to find, so the actual match is failing.

I **think** this is fixed in the `v1` branch, but I'm keeping this bug open until I can confirm it. Thanks a lot for the reproducible test case!

**Comment by bdombro** [comment] 2017-11-07 02:32
My pleasure!

**Comment by pixelastic** [comment] 2017-11-17 19:35
I've just soft released [jekyll-algolia](https://github.com/algolia/jekyll-algolia) as a successor to this plugin. I've tested your markup with this new version and everything seems to be working smoothly.

I'm closing this issue for now, but let me know if you still have errors by posting on the other repo issue tracker: https://github.com/algolia/jekyll-algolia/issues

Thanks for the report in the first place!

**Closed as completed by pixelastic** 2017-11-17 19:35 UTC
Labels: bug, v1
