### ISSUE TITLE
Timeout at indexing time

### ISSUE THREAD

**Issue by Shipow** [algolia/algoliasearch-jekyll#41] opened 2016-09-12 12:34 UTC
Timeout on a poor bandwidth (350kb/s down- 35kb/s up) with 0.8.0
I tried the RC but it indexed only pages.

Here the project I used for those tests: https://github.com/Shipow/cleanflight-web

**Comment by pixelastic** [comment] 2016-09-18 18:28
Thanks. I'll give it a try (low on by backlog at the moment, but I'll get to it eventually).

**Comment by pixelastic** [comment] 2017-10-30 12:40
I'm closing this as it should be fixed by the lazy_update of the v1. Feel free to re-open if the issue is still present once v1 is released.

**Comment by Shipow** [comment] 2017-10-30 13:20
Can you let it opens until then? Happy to try it.

**Comment by pixelastic** [comment] 2017-10-31 09:02
Ok, re-opening it :)

**Comment by pixelastic** [comment] 2017-11-17 16:39
@Shipow I tried with the latest [jekyll-algolia](https://github.com/algolia/jekyll-algolia) version with my home connection and had no issue.

I had to do some minor changes to the configuration (for Jekyll 3). You can find my fork here: https://github.com/pixelastic/cleanflight-web/tree/issue-41 (I changed the application_id to mine, don't forget to revert)

Could you try and let me know if you still have the bandwidth issue? By default the new version tries to be  clever and only index new records. If it still fails, let me know your average up/down bandwidth so I can setup some tests on my side.

You also mentionned that only pages where indexed. What do you think should also be indexed? I only see pages in the repo.

**Comment by pixelastic** [comment] 2017-12-21 18:11
I'm closing this for now. Feel free to re-open on jekyll-algolia if you have other questions

**Closed as completed by pixelastic** 2017-12-21 18:11 UTC
Labels: pending
