### ISSUE TITLE
URL of pages are incomplete

### ISSUE THREAD

**Issue by nhoizey** [algolia/algoliasearch-jekyll#35] opened 2016-07-28 21:42 UTC
I use this plugin to index [my blog](https://nicolas-hoizey.com/). It indexes both posts and pages.

For example, a search for `algolia` lists 2 posts and 1 page:
https://nicolas-hoizey.com/recherche.html?q=algolia

The posts' URL are the good ones, but the page's URL misses the `.html` at the end.

**Comment by pixelastic** [comment] 2016-08-01 09:40
Interesting. Could you tell me which version of the plugin you're using?

**Comment by nhoizey** [comment] 2016-08-01 13:23
I'm not able to index anything currently, so I'll have to fix this first, sorry… :-/

**Comment by nhoizey** [comment] 2016-08-31 15:51
Sorry, my previous answer was out of topic.

I use this:
- algoliasearch-jekyll 0.8.0
- algoliasearch 1.10.0

**Comment by pixelastic** [comment] 2017-10-30 12:46
Could you tell me the other plugins (outside of Algolia) you're using on your Jekyll? I think one of them is messing with the parsing of the url. Or even better, if you have a repo where I can try it.

**Comment by DirtyF** [comment] 2017-10-30 13:03
Plugins are listed in the Gemfile:
https://github.com/nhoizey/nicolas-hoizey.com/blob/master/Gemfile#L8-L18

https://github.com/nhoizey/nicolas-hoizey.com

**Comment by pixelastic** [comment] 2017-10-31 09:02
Thanks!

**Comment by nhoizey** [comment] 2017-11-06 11:43
There are also a few plugins there:
https://github.com/nhoizey/nicolas-hoizey.com/tree/master/_plugins

**Comment by pixelastic** [comment] 2017-11-17 15:41
I've tried to reproduce the issue with the latest [jekyll-algolia](https://github.com/algolia/jekyll-algolia) but can't reproduce.

What I did was clone your repo, remove all mention of webmention (it was taking so much time to build the website I thought it was easier to just remove it). I managed to run `jekyll algolia` and get all the content updated.

I then checked on the Algolia dashboard and could see the final `.html` in the posts urls:
![image](https://user-images.githubusercontent.com/283419/32955227-b4c912f0-cbb5-11e7-8a38-73e7ebdbe5d6.png)

You mentioned that the issue only happens for pages and not posts, though. But I could not find any pages in your repo.

So maybe you changed the content of the repo since you opened the issue (it's more than one year old :sweat_smile:), or maybe the issue is triggered by webmention or, hopefully, the issue is fixed by the new version.

I'm keeping this issue open for now but if you think it's resolved, feel free to close it.

**Comment by pixelastic** [comment] 2017-11-17 15:42
Oh, and I forked your repo and pushed my "working" version here: https://github.com/pixelastic/nicolas-hoizey.com/tree/issue-35

**Comment by nhoizey** [comment] 2017-11-17 22:24
Here are some pages:
https://github.com/nhoizey/nicolas-hoizey.com/tree/master/a-propos

But I will try the new plugin and let you know if I still have the issue.

**Comment by pixelastic** [comment] 2017-11-18 00:59
Hmm, seems like Ubuntu and its home encrypted directory is preventing me from pulling repos where filenames are too long. It just stops in the middle of the checkout, leaving some files not downloaded.

I'm re-cloning the repo from an unencrypted directory and try again. I can definitely see the pages in the GitHub UI but not on my machine. I'll try again with your content once I've downloaded your 250MB again ;)

**Comment by pixelastic** [comment] 2017-11-18 01:16
I've managed to clone your repo but I'm now having an issue when running `jekyll build`:

```
Liquid Exception: No such file or directory @ dir_s_mkdir - .jekyll-cache/youtube in /tmp/nhoizey/nicolas-hoizey.com/_posts/2006/07/10-la-fievre-du-photographe/2006-07-10-la-fievre-du-photographe.md
```
Let me know if/when you managed to test the plugin; there isn't much I can do on my side for now.

**Comment by pixelastic** [comment] 2017-12-21 18:10
I'm closing this for now. Feel free to re-open it if you have similar issues with jekyll-algolia.

**Closed as completed by pixelastic** 2017-12-21 18:10 UTC
Labels: pending

**Comment by nhoizey** [comment] 2018-02-14 13:51
@pixelastic I just saw that I still have this issue, even with the new jekyll-algolia:

https://nicolas-hoizey.com/recherche.html?q=algolia

**Comment by nhoizey** [comment] 2018-02-14 15:46
@pixelastic should I open an issue on jekyll-algolia?

**Comment by pixelastic** [comment] 2018-02-14 16:44
Yes please :)
